CREATE DATABASE  if NOT EXISTS spider;
use spider;
CREATE TABLE IF NOT EXISTS userinfo (
    USER_NAME VARCHAR(40) NOT NULL unique,
    USER_PASSWD VARCHAR(100) NOT NULL,
    USER_SALT VARCHAR(64) NOT NULL,
    USER_MAIL VARCHAR(40) NOT NULL unique,
    SUBMISSION_DATE VARCHAR(40),
    PRIMARY KEY (USER_MAIL)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8;