CREATE DATABASE  if NOT EXISTS spider;
use spider;
CREATE TABLE IF NOT EXISTS userinfo (
    USER_ID INT AUTO_INCREMENT,
    USER_NAME VARCHAR(40) NOT NULL,
    USER_PASSWD VARCHAR(100) NOT NULL,
    SUBMISSION_DATE VARCHAR(40),
    PRIMARY KEY (USER_ID , USER_NAME)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8;